// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[project].tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/new-project.tsx";
import * as $$0 from "./islands/AddProject.tsx";
import * as $$1 from "./islands/ProjectData.tsx";
import * as $$2 from "./islands/Projects.tsx";

const manifest = {
  routes: {
    "./routes/[project].tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/new-project.tsx": $2,
  },
  islands: {
    "./islands/AddProject.tsx": $$0,
    "./islands/ProjectData.tsx": $$1,
    "./islands/Projects.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
